wirepas/backend-apis

- gateway_to_backend/protocol_buffers_files/otap_message.proto
- wrappers/python/wirepas_messaging/gateway/otap_message.proto
> Add comment about scratchpad buffer size

- wrappers/python/wirepas_messaging/__init__.py
- wrappers/python/wirepas_messaging/wpe/__init__.py
Removes the import of the private interface for WPE.
> WPE module imports

- .readthedocs.yml
- wrappers/python/docs/requirements.txt
- wrappers/python/docs/source/conf.py
This commit adds a method to copy and generate the proto
files during the sphynx build stage.
> Copy and generate protos during sphinx builds

- .ci/build.sh
- .ci/install-requirements.sh
- .ci/install.sh
- .travis.yml
- wrappers/python/tests/run_all_examples.sh
- wrappers/python/utils/compile_protos.sh
- wrappers/python/utils/generate_wheel.sh
- wrappers/python/utils/pull_protos.sh
This changes runs the tests on each PR and commit to master.
It adds the exit flag to most bash scripts where it was missing.
> Build enhancements

- wrappers/python/wirepas_messaging/wnt/__init__.py
> Update WNT ws_api import

- wrappers/python/examples/create_gateway_messages.py
- wrappers/python/examples/create_wnt_messages.py
- wrappers/python/examples/create_wpe_messages.py
- wrappers/python/wirepas_messaging/__main__.py
- wrappers/python/wirepas_messaging/gateway/api/test/default_value.py
- wrappers/python/wirepas_messaging/gateway/api/test/test_get_configs.py
- wrappers/python/wirepas_messaging/gateway/api/test/test_get_gw_info.py
- wrappers/python/wirepas_messaging/gateway/api/test/test_get_scratchpad_status.py
- wrappers/python/wirepas_messaging/gateway/api/test/test_process_scratchpad.py
- wrappers/python/wirepas_messaging/gateway/api/test/test_received_data.py
- wrappers/python/wirepas_messaging/gateway/api/test/test_send_data.py
- wrappers/python/wirepas_messaging/gateway/api/test/test_set_config.py
- wrappers/python/wirepas_messaging/gateway/api/test/test_status.py
- wrappers/python/wirepas_messaging/gateway/api/test/test_upload_scratchpad.py
- wrappers/python/wirepas_messaging/wnt/ws_api/applicationconfigurationmessages.py
- wrappers/python/wirepas_messaging/wnt/ws_api/areamessages.py
- wrappers/python/wirepas_messaging/wnt/ws_api/authenticationmessages.py
- wrappers/python/wirepas_messaging/wnt/ws_api/buildingmessages.py
- wrappers/python/wirepas_messaging/wnt/ws_api/componentsinformation.py
- wrappers/python/wirepas_messaging/wnt/ws_api/floorplanmessages.py
- wrappers/python/wirepas_messaging/wnt/ws_api/messagesbase.py
- wrappers/python/wirepas_messaging/wnt/ws_api/networkmessages.py
- wrappers/python/wirepas_messaging/wnt/ws_api/nodemessages.py
- wrappers/python/wirepas_messaging/wnt/ws_api/realtimesituationmessages.py
- wrappers/python/wirepas_messaging/wnt/ws_api/scratchpadstatus.py
This change contains the code formatted with black.
> Black pass

- wrappers/python/wirepas_messaging/wnt/ws_api/nodemessages.py
> Send node pixel position only with WNT protocol version 2

- wrappers/python/wirepas_messaging/wnt/ws_api/scratchpadstatusmessages.py
> Add missing doc string to scratchpad status messages

- wrappers/python/examples/wnt/nodedatamessage.py
- wrappers/python/wirepas_messaging/wnt/ws_api/__init__.py
- wrappers/python/wirepas_messaging/wnt/ws_api/nodedatamessagemessages.py
> Add sending of the WNT node data message example

- wrappers/python/examples/wnt/__init__.py
- wrappers/python/examples/wnt/applicationconfiguration.py
- wrappers/python/examples/wnt/authentication.py
- wrappers/python/examples/wnt/building.py
- wrappers/python/examples/wnt/componentsinformation.py
- wrappers/python/examples/wnt/floorplan.py
- wrappers/python/examples/wnt/floorplanarea.py
- wrappers/python/examples/wnt/network.py
- wrappers/python/examples/wnt/node.py
- wrappers/python/examples/wnt/nodedatamessage.py
- wrappers/python/examples/wnt/realtimedata.py
- wrappers/python/examples/wnt/requirements.txt
- wrappers/python/examples/wnt/scratchpadstatus.py
> Fix wnt examples imports and requirements

- wrappers/python/examples/wnt/README.md
- wrappers/python/examples/wnt/applicationconfiguration.py
- wrappers/python/examples/wnt/authentication.py
- wrappers/python/examples/wnt/building.py
- wrappers/python/examples/wnt/componentsinformation.py
- wrappers/python/examples/wnt/floorplan.py
- wrappers/python/examples/wnt/floorplanarea.py
- wrappers/python/examples/wnt/network.py
- wrappers/python/examples/wnt/node.py
- wrappers/python/examples/wnt/nodedatamessage.py
- wrappers/python/examples/wnt/realtimedata.py
- wrappers/python/examples/wnt/requirements.txt
- wrappers/python/examples/wnt/scratchpadstatus.py
- wrappers/python/examples/wnt/utils.py
- wrappers/python/requirements.txt
- wrappers/python/tests/requirements.txt
- wrappers/python/tests/wnt/test_approvemultiplenodes.py
- wrappers/python/tests/wnt/test_createuser.py
- wrappers/python/tests/wnt/test_deleteuser.py
- wrappers/python/tests/wnt/test_login.py
- wrappers/python/tests/wnt/test_queryusers.py
- wrappers/python/tests/wnt/test_updateuser.py
- wrappers/python/tests/wnt/utils.py
> Add README.md to WNT examples

- wrappers/python/README.md
> Add information about the examples to the main readme

- .ci/deploy-pypi.sh
- .travis.yml
Fix the location for the changelog and the python dist folder
> Fix changelog and dist path in Travis pipeline

- README.md
- wrappers/python/README.md
- wrappers/python/wirepas_messaging/__about__.py
In preparation for v1.3.0 release
> Update python version

- gateway_to_backend/README.md
Gateway info topic was mentionned as get_gw_info and get_gateway_info
The right one is get_gw_info
> Fix inconsistency in doc

- gateway_to_backend/README.md
- gateway_to_backend/protocol_buffers_files/config_message.proto
- gateway_to_backend/protocol_buffers_files/generic_message.proto
- gateway_to_backend/protocol_buffers_files/otap_message.proto
Doc must be updated later to have permanent link (from master sha1)
> GatewayToBackend API: add otap target related changes

- wnt/protocol_buffers_files/message.proto
- wnt/protocol_buffers_files/otap.proto
> Update WNT protos for WNT 4.1

- gateway_to_backend/protocol_buffers_files/config_message.proto
Detail the meaning of the StatusEvent's version
> Add description of version field in StatusEvent message definition

- wnt/protocol_buffers_files/commons.proto
- wnt/protocol_buffers_files/message.proto
- wnt/protocol_buffers_files/otap.proto
- wnt/protocol_buffers_files/remote_api.proto
> Update WNT protos for WNT 4.2

- wpe/protocol_buffers_files/google/protobuf/descriptor.proto
- wpe/protocol_buffers_files/nanopb.proto
- wpe/protocol_buffers_files/public.proto
> Update WPE protos to 1.6.0

- wnt/protocol_buffers_files/commons.proto
- wnt/protocol_buffers_files/internal.proto
- wnt/protocol_buffers_files/message.proto
> Update WNT protos to 4.3.0

- wnt/protocol_buffers_files/internal.proto
- wnt/protocol_buffers_files/message.proto
> Update WNT protos to 4.4.0

- wpe/protocol_buffers_files/public.proto
> Update WPE protos to 1.7.0

- wnt/protocol_buffers_files/google/protobuf/descriptor.proto
- wpe/protocol_buffers_files/google/protobuf/descriptor.proto
Update descriptor proto for WNT and WPE
Needed for WPE to get "allow_alias" option working
> Update descriptor proto for WNT and WPE

- wnt/protocol_buffers_files/commons.proto
- wnt/protocol_buffers_files/internal.proto
- wnt/protocol_buffers_files/message.proto
> Update protos for WNT 4.4.1

- gateway_to_backend/README.md
Only using the first line number instead of range, since it's easier to update
> Update message links in the readme
